package store

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"unicode/utf8"

	"github.com/noamsto/hookyard/cmd/priors/internal/atomicfile"
	"github.com/noamsto/hookyard/cmd/priors/internal/fact"
	"github.com/noamsto/hookyard/cmd/priors/internal/gate"
	"github.com/noamsto/hookyard/cmd/priors/internal/sanitize"
)

const (
	IndexFile     = "MEMORY.md"
	MaxIndexLines = 200
	MaxIndexBytes = 25 * 1024

	indexMarker = "<!-- generated by priors index; do not edit -->\n"
	// maxIndexRel keeps the "- [name](rel) — " prefix well inside
	// sanitize.IndexLineMax, so a description always has room.
	maxIndexRel = 200
)

var (
	relRE       = regexp.MustCompile(`^[A-Za-z0-9._/-]+\.md$`)
	indexLineRE = regexp.MustCompile(`^- \[([^\]]+)\]\(([^)]+)\) —(?: |$)`)
)

// IndexLines is the index body for entries: live facts, newest first, cut so
// that the root's whole MEMORY.md, frame included, fits MaxIndexLines lines
// and MaxIndexBytes bytes. Lines are built from the parsed fact rather than
// sanitized whole, because sanitizing is not idempotent and would rewrite a
// name that merely resembles a fence token.
func (r Root) IndexLines(entries []Entry) []string {
	live := make([]Entry, 0, len(entries))
	for _, e := range entries {
		if !e.Archived && e.Fact.Metadata.SupersededBy == "" && indexable(e.Fact.Name, e.Rel) {
			live = append(live, e)
		}
	}
	slices.SortFunc(live, func(a, b Entry) int {
		if c := b.Fact.ModifiedTime().Compare(a.Fact.ModifiedTime()); c != 0 {
			return c
		}
		if c := strings.Compare(a.Fact.Name, b.Fact.Name); c != 0 {
			return c
		}
		return strings.Compare(a.Rel, b.Rel)
	})

	frame := r.indexFile("", sanitize.NewDelimiter())
	maxLines := MaxIndexLines - strings.Count(frame, "\n")
	maxBytes := MaxIndexBytes - len(frame)
	var lines []string
	size := 0
	for _, e := range live {
		line := indexLine(e)
		if len(lines) == maxLines || size+len(line)+1 > maxBytes {
			break
		}
		lines = append(lines, line)
		size += len(line) + 1
	}
	return lines
}

// indexable reports whether name and rel can sit in an index line without
// breaking out of its "- [name](rel) — " frame.
func indexable(name, rel string) bool {
	return fact.NameRE.MatchString(name) && relRE.MatchString(rel) && len(rel) <= maxIndexRel
}

func indexLine(e Entry) string {
	prefix := "- [" + e.Fact.Name + "](" + e.Rel + ") — "
	room := sanitize.IndexLineMax - utf8.RuneCountInString(prefix)
	return strings.TrimRight(prefix+sanitize.Line(e.Fact.Description, room), " ")
}

// ParseIndexLine splits "- [name](rel) — …". Only lines WriteIndex could
// have produced parse.
func ParseIndexLine(line string) (name, rel string, ok bool) {
	m := indexLineRE.FindStringSubmatch(line)
	if m == nil || !indexable(m[1], m[2]) {
		return "", "", false
	}
	return m[1], m[2], true
}

// Unredacted drops the entries whose file bytes match a redaction rule and
// reports each one by path and rule id, never by its text.
func Unredacted(entries []Entry, rules gate.Rules) (kept []Entry, reports []string) {
	for _, e := range entries {
		if ids := rules.Match(string(e.Raw)); len(ids) > 0 {
			reports = append(reports, fmt.Sprintf("excluded %s: rule %s", e.Rel, strings.Join(ids, ",")))
			continue
		}
		kept = append(kept, e)
	}
	return kept, reports
}

// WriteIndex regenerates MEMORY.md and reports whether the file changed. An
// index that already holds exactly the wanted lines is left untouched, so
// regenerating is idempotent and does not dirty a git checkout. The reports
// name each file the walk skipped and each fact the rules kept out.
func (r Root) WriteIndex(rules gate.Rules) (changed bool, reports []string, err error) {
	if r.Path == "" {
		return false, nil, errors.New("store has no path")
	}
	entries, errs := r.Walk()
	for _, e := range errs {
		reports = append(reports, fmt.Sprintf("skipped %s: %v", e.Rel, e.Err))
	}
	entries, excluded := Unredacted(entries, rules)
	reports = append(reports, excluded...)
	lines := r.IndexLines(entries)

	path := filepath.Join(r.Path, IndexFile)
	if b, err := os.ReadFile(path); err == nil { //nolint:gosec // path is the store's own MEMORY.md
		if have, ok := sanitize.Unfence(string(b)); ok && slices.Equal(have, lines) {
			return false, reports, nil
		}
	}

	body := ""
	if len(lines) > 0 {
		body = strings.Join(lines, "\n") + "\n"
	}
	if err := atomicfile.Write(path, []byte(r.indexFile(body, sanitize.NewDelimiter())), 0o644); err != nil {
		return false, reports, err
	}
	return true, reports, nil
}

func (r Root) indexFile(body, delim string) string {
	return indexMarker + sanitize.Fence(sanitize.Header(r.label()), body, delim)
}

func (r Root) label() string {
	switch r.Kind {
	case KindQuarantine:
		return "quarantine"
	case KindLocal:
		return string(r.Store) + " store, local (unsynced, flagged)"
	case KindCheckout:
	}
	return string(r.Store) + " store"
}

// ReadIndex returns the lines between the index's own fence.
func (r Root) ReadIndex() ([]string, error) {
	b, err := os.ReadFile(filepath.Join(r.Path, IndexFile))
	if err != nil {
		return nil, err
	}
	lines, ok := sanitize.Unfence(string(b))
	if !ok {
		return nil, fmt.Errorf("%s has no intact fence", IndexFile)
	}
	return lines, nil
}
