package render

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/noamsto/hookyard/internal/atomicfile"
)

const (
	codexBegin = "# hookyard-managed: begin — regenerated by `hookyard install`, do not edit"
	codexEnd   = "# hookyard-managed: end"
)

type codexHook struct {
	Type     string `toml:"type"`
	Command  string `toml:"command"`
	Timeout  int    `toml:"timeout"`
	Hookyard bool   `toml:"hookyard"`
}

type codexMatcher struct {
	Matcher string `toml:"matcher"`
}

// WriteCodex renders entries into ~/.codex/config.toml as a marker-guarded
// block appended to whatever is already there.
//
// It deliberately does not rewrite the file as TOML. That file holds
// substantial content hookyard must not touch — model selection, mcp_servers,
// and two trust stores: [hooks.state], which records per-entry hook trust, and
// [projects], which records per-directory trust. Regenerating the file would
// revoke every project the user has trusted and every hook they have reviewed,
// which they would experience as Codex abruptly distrusting their machine. So
// the block is spliced textually and every other byte survives verbatim; TOML
// is used to *validate* the inherited file and to *encode* hookyard's own
// block, never to re-emit someone else's.
func WriteCodex(path string, entries []Entry) error {
	raw, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	existing := string(raw)

	// config.toml is Codex's own file, carrying trust stores hookyard must
	// never touch un-asked. A zero-entry plan with no prior hookyard block to
	// strip has nothing to add and nothing to remove, so it takes no rename
	// at all and leaves the file exactly as Codex last wrote it.
	if len(entries) == 0 && !codexOwnsContent(existing) {
		return nil
	}

	if strings.TrimSpace(existing) != "" {
		var probe map[string]any
		if _, err := toml.Decode(existing, &probe); err != nil {
			return fmt.Errorf("%s is not valid TOML, refusing to overwrite it: %w", path, err)
		}
	}

	stripped, err := stripCodexBlock(existing, path)
	if err != nil {
		return err
	}

	out := stripped
	if len(entries) > 0 {
		block, err := encodeCodexBlock(entries)
		if err != nil {
			return err
		}
		if out != "" && !strings.HasSuffix(out, "\n\n") {
			out = strings.TrimRight(out, "\n") + "\n\n"
		}
		out += block
	}

	// The inherited content was already valid and the block came from an
	// encoder, but the splice itself is new text: check the result parses
	// before it replaces a working config.
	var probe map[string]any
	if _, err := toml.Decode(out, &probe); err != nil {
		return fmt.Errorf("rendering %s would produce invalid TOML, refusing to write: %w", path, err)
	}
	// This is a file render does not own, so a pre-existing one keeps its
	// perm bits; one hookyard creates starts at 0600, matching how Codex
	// ships its own.
	mode := os.FileMode(0o600)
	if info, err := os.Stat(path); err == nil {
		mode = info.Mode().Perm()
	}
	return atomicfile.Write(path, []byte(out), mode)
}

// encodeCodexBlock assembles the block with explicit array-of-table headers
// and lets the TOML encoder produce every value.
//
// Encoding the whole block as one struct would emit a bare [hooks] header,
// which the deployed config never carries and which redefines a table the
// inherited file has already opened as [hooks.state]. Headers are built here
// instead; they contain no manifest-supplied text beyond an event name, which
// validation constrains to an identifier, while every string that could carry
// a quote or a newline goes through the encoder.
func encodeCodexBlock(entries []Entry) (string, error) {
	var buf strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&buf, "\n[[hooks.%s]]\n", e.Event)
		if e.Matcher != "" {
			encoded, err := encodeTOML(codexMatcher{Matcher: e.Matcher})
			if err != nil {
				return "", err
			}
			buf.WriteString(encoded)
		}
		fmt.Fprintf(&buf, "\n[[hooks.%s.hooks]]\n", e.Event)
		encoded, err := encodeTOML(codexHook{
			Type:     "command",
			Command:  e.Command,
			Timeout:  EmittedTimeoutSeconds,
			Hookyard: true,
		})
		if err != nil {
			return "", err
		}
		buf.WriteString(encoded)
	}
	return buf.String(), nil
}

func encodeTOML(v any) (string, error) {
	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(v); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func codexOwnsContent(s string) bool {
	return strings.Contains(s, "route --registered-for codex") ||
		strings.Contains(s, "hookyard = true") ||
		strings.Contains(s, "# hookyard-managed:")
}

type tomlSection struct {
	header string
	raw    string
}

func isTOMLHeaderLine(line string) bool {
	for _, r := range line {
		if r == ' ' || r == '\t' {
			continue
		}
		return r == '['
	}
	return false
}

func splitTOMLSections(content string) (string, []tomlSection) {
	var headers []int
	i := 0
	for i < len(content) {
		lineStart := i
		nl := strings.IndexByte(content[i:], '\n')
		var line string
		if nl < 0 {
			line = content[i:]
			i = len(content)
		} else {
			line = content[i : i+nl]
			i += nl + 1
		}
		if isTOMLHeaderLine(line) {
			headers = append(headers, lineStart)
		}
	}
	if len(headers) == 0 {
		return content, nil
	}
	preamble := content[:headers[0]]
	sections := make([]tomlSection, 0, len(headers))
	for j, start := range headers {
		end := len(content)
		if j+1 < len(headers) {
			end = headers[j+1]
		}
		raw := content[start:end]
		header := raw
		if nl := strings.IndexByte(raw, '\n'); nl >= 0 {
			header = raw[:nl]
		}
		sections = append(sections, tomlSection{header: header, raw: raw})
	}
	return preamble, sections
}

func parseHooksArrayHeader(header string) (event string, inner bool, ok bool) {
	s := strings.TrimSpace(header)
	if !strings.HasPrefix(s, "[[") || !strings.HasSuffix(s, "]]") {
		return "", false, false
	}
	name := s[2 : len(s)-2]
	if !strings.HasPrefix(name, "hooks.") {
		return "", false, false
	}
	rest := strings.TrimPrefix(name, "hooks.")
	if strings.HasSuffix(rest, ".hooks") {
		event = strings.TrimSuffix(rest, ".hooks")
		return event, true, event != ""
	}
	return rest, false, rest != ""
}

func sectionHasCommandLine(raw string) bool {
	nl := strings.IndexByte(raw, '\n')
	if nl < 0 {
		return false
	}
	body := raw[nl+1:]
	for _, line := range strings.Split(body, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "command") {
			return true
		}
	}
	return false
}

func dropLegacyMarkerLines(content string) string {
	lines := strings.Split(content, "\n")
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		t := strings.TrimSpace(line)
		if t == codexBegin || t == codexEnd {
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}

func collapseNewlines(s string) string {
	for strings.Contains(s, "\n\n\n") {
		s = strings.ReplaceAll(s, "\n\n\n", "\n\n")
	}
	return s
}

func stripCodexBlockOnce(content, path string) (string, bool, error) {
	preamble, sections := splitTOMLSections(content)
	if len(sections) == 0 {
		return content, false, nil
	}
	drop := make([]bool, len(sections))
	for i, sec := range sections {
		if !strings.Contains(sec.header, ".hooks]]") {
			continue
		}
		owned := strings.Contains(sec.raw, "hookyard = true") ||
			strings.Contains(sec.raw, "route --registered-for codex")
		if !owned {
			continue
		}
		event, inner, ok := parseHooksArrayHeader(sec.header)
		if !ok || !inner {
			return "", false, fmt.Errorf("%s: cannot parse hookyard-owned table header %q", path, strings.TrimSpace(sec.header))
		}
		drop[i] = true
		if i == 0 {
			continue
		}
		prev := sections[i-1]
		if strings.Contains(prev.header, ".hooks") {
			continue
		}
		prevEvent, prevInner, prevOK := parseHooksArrayHeader(prev.header)
		if !prevOK || prevInner || prevEvent != event {
			continue
		}
		if sectionHasCommandLine(prev.raw) {
			continue
		}
		drop[i-1] = true
	}
	changed := false
	for _, d := range drop {
		if d {
			changed = true
			break
		}
	}
	if !changed {
		return content, false, nil
	}
	var b strings.Builder
	b.WriteString(preamble)
	for i, sec := range sections {
		if drop[i] {
			continue
		}
		b.WriteString(sec.raw)
	}
	return b.String(), true, nil
}

func stripCodexBlock(content, path string) (string, error) {
	for {
		next, changed, err := stripCodexBlockOnce(content, path)
		if err != nil {
			return "", err
		}
		if !changed {
			break
		}
		content = next
	}
	out := collapseNewlines(dropLegacyMarkerLines(content))
	out = strings.TrimSpace(out)
	if out == "" {
		return "", nil
	}
	return out + "\n", nil
}
