package render

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/noamsto/hookyard/internal/atomicfile"
)

const (
	codexBegin = "# hookyard-managed: begin — regenerated by `hookyard install`, do not edit"
	codexEnd   = "# hookyard-managed: end"
)

type codexHook struct {
	Type    string `toml:"type"`
	Command string `toml:"command"`
	Timeout int    `toml:"timeout"`
}

type codexMatcher struct {
	Matcher string `toml:"matcher"`
}

// WriteCodex renders entries into ~/.codex/config.toml as a marker-guarded
// block appended to whatever is already there.
//
// It deliberately does not rewrite the file as TOML. That file holds
// substantial content hookyard must not touch — model selection, mcp_servers,
// and two trust stores: [hooks.state], which records per-entry hook trust, and
// [projects], which records per-directory trust. Regenerating the file would
// revoke every project the user has trusted and every hook they have reviewed,
// which they would experience as Codex abruptly distrusting their machine. So
// the block is spliced textually and every other byte survives verbatim; TOML
// is used to *validate* the inherited file and to *encode* hookyard's own
// block, never to re-emit someone else's.
func WriteCodex(path string, entries []Entry) error {
	raw, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	existing := string(raw)

	// config.toml is Codex's own file, carrying trust stores hookyard must
	// never touch un-asked. A zero-entry plan with no prior hookyard block to
	// strip has nothing to add and nothing to remove, so it takes no rename
	// at all and leaves the file exactly as Codex last wrote it.
	if len(entries) == 0 && !strings.Contains(existing, codexBegin) {
		return nil
	}

	if strings.TrimSpace(existing) != "" {
		var probe map[string]any
		if _, err := toml.Decode(existing, &probe); err != nil {
			return fmt.Errorf("%s is not valid TOML, refusing to overwrite it: %w", path, err)
		}
	}

	stripped, err := stripCodexBlock(existing, path)
	if err != nil {
		return err
	}

	out := stripped
	if len(entries) > 0 {
		block, err := encodeCodexBlock(entries)
		if err != nil {
			return err
		}
		if out != "" && !strings.HasSuffix(out, "\n\n") {
			out = strings.TrimRight(out, "\n") + "\n\n"
		}
		out += block
	}

	// The inherited content was already valid and the block came from an
	// encoder, but the splice itself is new text: check the result parses
	// before it replaces a working config.
	var probe map[string]any
	if _, err := toml.Decode(out, &probe); err != nil {
		return fmt.Errorf("rendering %s would produce invalid TOML, refusing to write: %w", path, err)
	}
	// This is a file render does not own, so a pre-existing one keeps its
	// perm bits; one hookyard creates starts at 0600, matching how Codex
	// ships its own.
	mode := os.FileMode(0o600)
	if info, err := os.Stat(path); err == nil {
		mode = info.Mode().Perm()
	}
	return atomicfile.Write(path, []byte(out), mode)
}

// encodeCodexBlock assembles the block with explicit array-of-table headers
// and lets the TOML encoder produce every value.
//
// Encoding the whole block as one struct would emit a bare [hooks] header,
// which the deployed config never carries and which redefines a table the
// inherited file has already opened as [hooks.state]. Headers are built here
// instead; they contain no manifest-supplied text beyond an event name, which
// validation constrains to an identifier, while every string that could carry
// a quote or a newline goes through the encoder.
func encodeCodexBlock(entries []Entry) (string, error) {
	var buf strings.Builder
	buf.WriteString(codexBegin + "\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\n[[hooks.%s]]\n", e.Event)
		if e.Matcher != "" {
			encoded, err := encodeTOML(codexMatcher{Matcher: e.Matcher})
			if err != nil {
				return "", err
			}
			buf.WriteString(encoded)
		}
		fmt.Fprintf(&buf, "\n[[hooks.%s.hooks]]\n", e.Event)
		encoded, err := encodeTOML(codexHook{
			Type:    "command",
			Command: e.Command,
			Timeout: EmittedTimeoutSeconds,
		})
		if err != nil {
			return "", err
		}
		buf.WriteString(encoded)
	}
	buf.WriteString(codexEnd + "\n")
	return buf.String(), nil
}

func encodeTOML(v any) (string, error) {
	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(v); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func stripCodexBlock(content, path string) (string, error) {
	begin := strings.Index(content, codexBegin)
	if begin < 0 {
		return content, nil
	}
	end := strings.Index(content[begin:], codexEnd)
	if end < 0 {
		return "", fmt.Errorf("%s has a hookyard block that starts but never ends; "+
			"refusing to guess where it stops", path)
	}
	tail := content[begin+end+len(codexEnd):]
	return strings.TrimRight(content[:begin], "\n") + strings.TrimLeft(tail, "\n"), nil
}
