//go:build ignore

// gen_confusables derives confusableSets from the pinned UTS #39
// confusables.txt. Run via go generate.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"slices"
	"strconv"
	"strings"
	"unicode"
)

const (
	version = "18.0.0"
	url     = "https://www.unicode.org/Public/" + version + "/security/confusables.txt"
	sum     = "6ed3ee967c9dfdf6677d563c9985182fbc50a2efb7d6059cd57b2e2ce18f5b92"
)

// imageBit duplicates the package's: this file is ignore-tagged and cannot
// import it.
func imageBit(r rune) uint64 {
	switch {
	case 'a' <= r && r <= 'z':
		return 1 << (r - 'a')
	case '0' <= r && r <= '9':
		return 1 << (26 + r - '0')
	case r == '=':
		return 1 << 36
	}
	return 0
}

func main() {
	resp, err := http.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("GET %s: %s", url, resp.Status)
	}
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	h := sha256.Sum256(data)
	if got := hex.EncodeToString(h[:]); got != sum {
		log.Fatalf("confusables.txt sha256 = %s, want %s", got, sum)
	}

	targets := parse(strings.TrimPrefix(string(data), "\ufeff"))

	var protos []rune
	for _, r := range "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz=" {
		protos = append(protos, r)
	}
	proto := func(x rune) string {
		if t, ok := targets[x]; ok {
			return t
		}
		return string(x)
	}

	var keys []rune
	masks := map[rune]uint64{}
	for c, t := range targets {
		if c < 0x80 {
			continue
		}
		var mask uint64
		for _, x := range protos {
			if proto(x) == t {
				mask |= imageBit(unicode.ToLower(x))
			}
		}
		if mask != 0 {
			keys = append(keys, c)
			masks[c] = mask
		}
	}
	slices.Sort(keys)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen_confusables.go; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: UTS #39 confusables.txt version %s\n", version)
	fmt.Fprintf(&b, "// URL: %s\n", url)
	fmt.Fprintf(&b, "// SHA-256: %s\n\n", sum)
	fmt.Fprintf(&b, "package sanitize\n\n")
	fmt.Fprintf(&b, "// confusableSets maps a non-ASCII rune to the ASCII letters, digits and '='\n")
	fmt.Fprintf(&b, "// it is confusable with, as imageBit bits.\n")
	fmt.Fprintf(&b, "var confusableSets = map[rune]uint64{\n")
	for _, c := range keys {
		fmt.Fprintf(&b, "\t0x%04x: 0x%x,\n", c, masks[c])
	}
	fmt.Fprintf(&b, "}\n")

	out, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("confusables_table.go", out, 0o644); err != nil {
		log.Fatal(err)
	}
}

// parse reads `SRC ;\tTARGET ;\tMA\t# ...` lines into source -> target.
func parse(text string) map[rune]string {
	targets := map[rune]string{}
	for line := range strings.SplitSeq(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, ";")
		if len(fields) < 3 {
			log.Fatalf("malformed line: %q", line)
		}
		src, err := strconv.ParseUint(strings.TrimSpace(fields[0]), 16, 32)
		if err != nil {
			log.Fatalf("bad source in %q: %v", line, err)
		}
		var t strings.Builder
		for _, f := range strings.Fields(fields[1]) {
			cp, err := strconv.ParseUint(f, 16, 32)
			if err != nil {
				log.Fatalf("bad target in %q: %v", line, err)
			}
			t.WriteRune(rune(cp))
		}
		targets[rune(src)] = t.String()
	}
	return targets
}
